### ISSUE TITLE
Pubby map issue

### ISSUE THREAD

**Issue by AsaiasWolffe** [hrzntal/horizon#727]
### Description of the Issue

![image](https://user-images.githubusercontent.com/59212063/150610466-351bc884-9c4a-4ad5-8d1a-7a71c6baf18e.png)
Light in front of the console in the circuitry lab in science

**Comment by KathrinBailey** [comment]
-- Apologies in advance these are all really nitpicky.
![image](https://user-images.githubusercontent.com/53862927/150685626-a0e387ad-3a14-48c0-b71a-ead4b706429a.png)
Reinforced walls around bedroom (inconsistent with other head bedrooms)
--
![image](https://user-images.githubusercontent.com/53862927/150685708-5b81f2f7-dfed-429c-9446-aba06a67a76f.png)
Circled wall should be normal instead of reinforced
--
![image](https://user-images.githubusercontent.com/53862927/150685753-e9c05831-9b70-49e8-8c39-868e64addfb8.png)
Circled walls should be reinforced
--
Missing clown spawn (feature?), only mime spawn present.
--
![image](https://user-images.githubusercontent.com/53862927/150686002-b0ea7197-ca70-434d-8f7f-f16183c23d81.png)
Pretty much all of the walls inside of security have a weird mixture of random reinforced walls and normal walls, specifically around the labour shuttle, they need normalising.
--
![image](https://user-images.githubusercontent.com/53862927/150686135-0c020efc-a5dc-4245-8496-67a10bbe3be1.png)
Weird rwalls protecting maint
--
![image](https://user-images.githubusercontent.com/53862927/150686203-872bd4fa-a9c1-4b97-a12e-5bb3bb9e0602.png)
Fox is missing blanket, please fix and provide blanket to waf-going fox.
--

**Comment by atakiya** [comment]
Stale?
Reopen if those issues still exist.

For new issues, please open one issue per bug/fault/improvement.
You *can* create a master-checklist, but each issue should still be separate wherever possible.
