### ISSUE TITLE
Ghost role bank accounts

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#986]
### Type of Request

Addition

### About the Request

To make the hotel actually function correctly, Right now everything is just free, like vendors. there's no good way to make bank accounts even for admins, you have to bruteforce a new account in in varedit.

### Why should this Idea be considered

Something that can be added to other additional ruins and station stuff untill we have the secondary crew stuff.

**Comment by atakiya** [comment]
This should be tied in with ATMs, people being able to make accounts via IDs with them.

**Comment by atakiya** [comment]
As found out, there is a machine that can do this, so this can be closed for now.
There are a lot of adjustments and improvements possible, but some map adjustments will do for now which is out of scope of this issue.

For stuff like, having an app replace the machine, map implementations or otherwise, please open other, specific issues, if wanted/required.
